### ISSUE TITLE
`panic: ftfy: PythonDir must be set

### ISSUE THREAD

**Issue by SHECA-Alvin** [pkimetal/pkimetal#66]
First of all, thanks for providing such a great project. I encountered a problem that I couldn't solve when using it.
When I run the image using k8s, the logs of k8s are as follows:
`panic: ftfy: PythonDir must be set
goroutine 1 [running]:
github.com/pkimetal/pkimetal/linter/ftfy.init.0()
	/app/linter/ftfy/handler.go:32 +0x1b6`

The mirror address is as follows：
docker pull ghcr.io/pkimetal/pkimetal:v1.3.2

**Comment by robstradling** [comment]
Hi.  The initialisation code [here](https://github.com/pkimetal/pkimetal/blob/main/linter/ftfy/handler.go#L28) should be automatically populating `PythonDir` using [this function](https://github.com/pkimetal/pkimetal/blob/main/linter/pipx.go#L33), which runs "pipx list" and parses the output to determine which Python version the package (ftfy or pkilint) was installed with.

Here's what I see when I use Docker to run "pipx list" in the container:
```
> docker run -p 8080:8080 -p 8081:8081 -it ghcr.io/pkimetal/pkimetal:v1.3.2 pipx list
venvs are in /root/.local/share/pipx/venvs
apps are exposed on your $PATH at /root/.local/bin
manual pages are exposed at /root/.local/share/man
   package ftfy 6.2.3, installed using Python 3.12.4
    - ftfy
   package pkilint 0.11.3, installed using Python 3.12.4
    - lint_cabf_serverauth_cert
    - lint_cabf_smime_cert
    - lint_crl
    - lint_etsi_cert
    - lint_ocsp_response
    - lint_pkix_cert
    - lint_pkix_signer_signee_cert_chain
```

Presumably the `GetPackageDetailsFromPipx` function is not behaving as expected when you're running it under k8s.  I don't yet understand why though.  We didn't encounter this problem when we deployed https://pkimet.al/ under k8s.

Do you see any other error messages in the pkimetal logging output prior to that panic?

**Comment by SHECA-Alvin** [comment]
Thank you very much for your reply!
I think your guess is right. I added logs in handler.go in the ftfy directory

The printed values ​​are as follows:
ftfyVersion: not installed
config.Config.Linter.Ftfy.PythonDir: autodetec

Please tell me your k8s version so that I can further troubleshoot the problem

**Comment by robstradling** [comment]
The https://pkimet.al/ deployment of pkimetal is currently running in GKE.  (We'll also be deploying pkimetal to our on-premise k8s clusters soon, but we're not quite there yet).

**Comment by SHECA-Alvin** [comment]
Thanks for your reply! Our operation and maintenance engineer has gone off work. Tomorrow, I will ask our engineer to obtain the print information of "pipx list" in the k8s environment and feedback to you!

**Comment by SHECA-Alvin** [comment]
Fortunately, we have found the cause of the problem and have solved it. Some configuration problems in our k8s caused some directories to be inaccessible, such as the root directory involved in this project, which led to the failure of "pipx list" to execute successfully. We have solved this problem by adjusting some configurations.

**Comment by SHECA-Alvin** [comment]
The results of executing "pipx list" are as follows:
Traceback(mostrecent call last):"/usr/lib/python3.12/pathlib.py", line 1311,in mkdirFileos.mkdir(self, mode)FileNotFoundError:[Errno 2]No such file or directory:’/.local/st
During handling of the above exception, another exception occurred
raceback(most recent call last):File"/usr/lib/python3.12/site-packages/pipx/main.py”, line 1018,return setup log file(
File"/usr/lib/python3.12/site-packages/pipx/main.py", line 999,pipx log dir.mkdir(parents=True, exist ok=True)Filein mkdir/usr/lib/python3.12/pathlib.py”,line 1315,self.parent.mkdir(parents=True,exist ok=True)File/usr/lib/python3.12/pathlib.py”,line 1315,in mkdirself.parent.mkdir(parents=True,exist okTrue)in mkdirFile"usr/lib/prthon3.12 pathlib.py，line 1315.self.parent.mkdir(parents=True,exist_ok=True)

**Comment by robstradling** [comment]
@SHECA-Alvin Thanks for following up.  I'm glad you were able to solve it!
